PKGDIR        ?= ../..
L4DIR	?= $(PKGDIR)/../l4re-snapshot-2014092821/src/l4

TARGET         = libl4revfs-fs-l4fs.a libl4revfs-fs-l4fs.so
LINK_INCR      = libl4revfs-fs-l4fs.a
PC_FILENAME    = libl4revfs-fs-l4fs
REQUIRES_LIBS  = libfs
SRC_CC         = l4fs.cc

include $(L4DIR)/mk/lib.mk
