PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../l4re-snapshot-2014092821/src/l4

# the default is to build the listed directories, provided that they
# contain a Makefile. If you need to change this, uncomment the following
# line and adapt it.
# TARGET = include src lib server examples doc

include $(L4DIR)/mk/subdir.mk
